### ISSUE TITLE
Docs: branch support

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#122]
Add support for checking out a different branch (`.e.g. staging`) via a `GIT_BRANCH` option. We should explain this only applies for the first clone and users can switch branches after

**Comment by matifali** [comment]
Accepting branch explicitly would improve the UX. It can already be done when git url contains tha branch name. e.g..

`https://github.com/coder/coder/tree/markdownlint`

Also discussed in #21

**Comment by bpmct** [comment]
Oh I see, we need to document this then
