### ISSUE TITLE
Add an extracting progress bar

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#124]
Extracting files can take 30s-2 minutes (see [envbuilder-benchmarks](https://github.com/coder/envbuilder-benchmarks)). Let's add some form of progress bar in the logs and/or in the Coder Ui to give users an assurance that the step is still running an expected end time.

**Comment by mtojek** [comment]
@mafredri Moving it back to the backlog as I think you haven't started it yet. Please move back if I'm wrong!
