### ISSUE TITLE
Update Dev Containers docs and example templates in Coder

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#131]
https://coder.com/docs/v2/latest/templates/dev-containers

- Say dev containers is no longer alpha
- Add more modern examples with the envbuilder image and Terraform docs new data sources

**Comment by bpmct** [comment]
We had an [internal ticket](https://coder.zendesk.com/agent/tickets/2859) about volume expansion in the aws-devcontainer template. A one-liner can be used to expand the filesystem (as seem in ticket and [AWS docs](https://docs.aws.amazon.com/ebs/latest/userguide/recognize-expanded-volume-linux.html)), but we also may want to reconsider our volume strategy in that template (e.g. do we really want to persist the root disk?)

**Comment by johnstcn** [comment]
> A one-liner can be used to expand the filesystem (as seem in ticket and [AWS docs](https://docs.aws.amazon.com/ebs/latest/userguide/recognize-expanded-volume-linux.html))

It's even easier than that: https://cloudinit.readthedocs.io/en/latest/reference/modules.html#growpart
