### ISSUE TITLE
☂️ v1.0 release

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#132]
We're planning on announcing a v1.0 release with performance improvements, quality of life features, and additional examples!

## Must have

- [x] https://github.com/coder/envbuilder/issues/128
  - [x] https://github.com/coder/kaniko/pull/12 
  - [x] https://github.com/coder/envbuilder/pull/213
  - [x] https://github.com/coder/envbuilder/issues/217
  - [x] https://github.com/coder/envbuilder/issues/216
- [x] 🆕 https://github.com/coder/envbuilder/issues/144
- [x] https://github.com/coder/envbuilder/issues/124
- [x] https://github.com/coder/envbuilder/issues/122
- [x] https://github.com/coder/envbuilder/issues/116
- [x] https://github.com/coder/envbuilder/issues/68
- [x] https://github.com/coder/envbuilder/issues/166
- [x] https://github.com/coder/envbuilder/issues/25
- [x] https://github.com/coder/envbuilder/issues/20
- [x] https://github.com/coder/envbuilder/issues/178
- [x] https://github.com/coder/envbuilder/issues/212

## Should have
- [x] https://github.com/coder/envbuilder/issues/126
- [x] https://github.com/coder/envbuilder/issues/129
- [x] https://github.com/coder/envbuilder/issues/31
- [x] https://github.com/coder/envbuilder/issues/130
- [x] 🆕 https://github.com/coder/envbuilder/issues/143
- [x] https://github.com/coder/envbuilder/issues/8
 - [x] https://github.com/coder/envbuilder/issues/218
 - [x] https://github.com/coder/envbuilder/issues/260
- [x] Terraform provider to support `--get-cached-image`
  - [ ] (perhaps document current 'hacky' workaround for Docker)
## Nice to have

- [ ] https://github.com/coder/envbuilder/issues/74
- [ ] https://github.com/coder/envbuilder/issues/43
- [ ] https://github.com/coder/envbuilder/issues/93
- [x] https://github.com/coder/envbuilder/issues/135

## Marketing / related 

- [x] https://github.com/coder/envbuilder/issues/131
  - [ ] Include (commented out) examples for using cache repo
- [ ] PR to add add Coder to projects in https://containers.dev
- [ ] Add to `awesome-devcontainers` repo
- [x] Refresh 💅 for the README.md https://github.com/coder/internal/issues/59
  - [ ] In particular, focus on non-Coder use cases, such as CI/CD or with code-server
- [ ] https://github.com/coder/envbuilder/issues/335

**Comment by bpmct** [comment]
moved #8 to should-have

**Comment by dal13002** [comment]
Hi,
Wondering if there is a timeline on when this will be released?

**Comment by mtojek** [comment]
@bpmct Here is the list of untracked issues in the milestone:

- [ ] https://github.com/coder/envbuilder/issues/231
- [ ] https://github.com/coder/envbuilder/issues/230
- [ ] https://github.com/coder/envbuilder/issues/236
- [ ] https://github.com/coder/envbuilder/issues/221
- [ ] https://github.com/coder/envbuilder/issues/220

Except for the first two (multi-stage), I would wait for some +1 👍s from community members to establish priorities.

Re _multi-stage_: @johnstcn are these a blocker for dogfood now?

**Comment by johnstcn** [comment]
@mtojek I wouldn't say so, no.

**Comment by bpmct** [comment]
@johnstcn I think we're good to cut a v1.0 once we fix #334. #231 also feels important but not critical

**Comment by johnstcn** [comment]
@bpmct is this good to close?

**Comment by bpmct** [comment]
Yep!
