### ISSUE TITLE
Investigate feasibility of `docker-compose` support

### ISSUE THREAD

**Issue by dannykopping** [coder/envbuilder#135]
https://containers.dev/implementors/json_reference/#compose-specific

This may not make it into the 1.0 release if we find that it doesn't fit the envbuilder model or requires lots of refactoring.

**Comment by shiipou** [comment]
Oh cool to see that issue, that can totally upgrade my experience to use it.

I hope my usecase can help : 

I have created a kubernetes template in coder v2 that use envbuilder and provide a DinD (Docker in Docker) sidecar.
That allow me to create my container using the `.devcontainer` specifications and I can start a database aside to use it in the workspace project.

Using the `dockerComposeFile` can allow to use the DinD sidecar to start the workspace.

Maybe that can be something like this for the implementation.

**Comment by bpmct** [comment]
Yeah, let's consider this out of scope for the v1.0 release and pick it back up depending on feedback

**Comment by mafredri** [comment]
Should we close this @bpmct if the investigation is complete?
