### ISSUE TITLE
Running envbuilder CLI on a local laptop may destroy the filesystem

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#144]
Can we add a warning that explains the CLI is not intended to be ran locally on a laptop (Macbook) and a warning of the outcome?

VM use cases are encouraged, but we should still warn

**Comment by bpmct** [comment]
FYI @mtojek

**Comment by matifali** [comment]
I have been through this :( Lost all my data.

**Comment by mtojek** [comment]
> I have been through this :( Lost all my data.

Can you share more details about what exactly happened? We may describe this in README.

**Comment by matifali** [comment]
I was logged in through SSH to a Linux VM and executed the `envbuilder` binary. I got disconnected and could not log in again. I assume it destroyed/overridden the filesystem.

**Comment by johnstcn** [comment]
While VM use-cases for envbuilder are definitely possible, its primary use-case is to run inside a container.

**Comment by johnstcn** [comment]
> I was logged in through SSH to a Linux VM and executed the `envbuilder` binary. I got disconnected and could not log in again. I assume it destroyed/overrode the filesystem.

I was able to reproduce this, but needed to run `envbuilder` as `root`.

**Comment by johnstcn** [comment]
Root cause: `util.DeleteFilesystem` will delete `KANIKO_DIR`.
In the envbuilder Dockerfile, we set `KANIKO_DIR=/.envbuilder`.
Otherwise, `KANIKO_DIR` defaults to `/`.
