### ISSUE TITLE
update docs with example for local-only usage

### ISSUE THREAD

**Issue by sam-goodwin** [coder/envbuilder#164]
I am trying to run the getting started command within my repo. I don't want to pull from git, I just want to build the image from my local file system with a locally cloned repository.

Have tried this:
```sh
docker run -it --rm \
  -v /tmp/envbuilder:/workspaces \
  -e DEVCONTAINER_DIR=.devcontainer \
  -e DEVCONTAINER_JSON_PATH=.devcontainer/devcontainer.json \
  ghcr.io/coder/envbuilder
```

No matter what I do, I get this error:
```
error: no Dockerfile or devcontainer.json found: no fallback image has been specified
error: no Dockerfile or devcontainer.json found: no fallback image has been specified
```

From the docs, it is not clear how to use this tool from a local git repository. It always assumes a hosted repo which is not what I am trying to do.

**Comment by sam-goodwin** [comment]
I genuinely have no idea how to use this tool without having a public Git repository and using `GIT_URL` which is meant to be optional. I think the docs could use some more examples.

**Comment by johnstcn** [comment]
The simplest way I've found to do this is to simply mount the repository to `/workspaces/empty`.

**Comment by johnstcn** [comment]
Fixed in https://github.com/coder/envbuilder/pull/342
