### ISSUE TITLE
bug: handle git URLs that are not valid URLs

### ISSUE THREAD

**Issue by johnstcn** [coder/envbuilder#175]
We cannot assume that anything folks pass to GIT_URL will be a valid URL.

Example:
```
error: parse "git@github.com:johnstcn/test-private-devcontainer.git": first path segment in URL cannot contain colon
```

**Comment by Forestsoft-de** [comment]
the issue comes from CloneRepo method. url.Parse is not a good solution for git url. Would this package a solution? https://pkg.go.dev/github.com/whilp/git-urls#section-documentation

I am on a fix right now because i need the ssh clone.
