### ISSUE TITLE
Update kaniko fork

### ISSUE THREAD

**Issue by matifali** [coder/envbuilder#178]
Coder's [kaniko](https://github.com/coder/kaniko) fork is outdated and prevents updating some of the dependencies that have vulnerabilities. 
Details can be seen here: https://github.com/coder/envbuilder/security/dependabot

This is a must-do before we launch 1.0
cc: @bpmct

**Comment by kylecarbs** [comment]
https://github.com/coder/kaniko/pull/7

**Comment by matifali** [comment]
Should we add a scheduled workflow to keep it in sync weekly or monthly?
https://github.com/wei/pull looks promising

**Comment by johnstcn** [comment]
Kaniko has since updated to go1.22 which means we also need to do so. Unfortunately our codersdk deps prevent this right now. For now I'm going to manually vendor these in.

**Comment by mtojek** [comment]
@johnstcn Is there anything left here or can we resolve this issue?

**Comment by johnstcn** [comment]
@mtojek https://github.com/coder/kaniko/pull/7 is still un-merged. Some of the tests are failing partially due to some changes we have that upstream does not.

Then https://github.com/coder/envbuilder/pull/195 can be updated and approved.

**Comment by johnstcn** [comment]
This is done now.
