### ISSUE TITLE
rename envbuilder.MagicDir to envbuilder.WorkingDir

### ISSUE THREAD

**Issue by johnstcn** [coder/envbuilder#184]
Not introduced by your PR but I want to point out that `MagicDir` is kinda unhelpful as a name; perhaps `EnvbuilderWorkingDir` would be more explicit?

_Originally posted by @dannykopping in https://github.com/coder/envbuilder/pull/183#discussion_r1598534110_

**Comment by leo-oliveira2** [comment]
Hello, can I do this?

**Comment by johnstcn** [comment]
> 1. Do we include a CLI change to rename the `MagicDirBase` option to `WorkingDirBase` in the scope for this issue? (please verify [@johnstcn](https://github.com/johnstcn)). I'm happy to do so. I just want the scope verified.

I would consider this in scope of this issue. It's not really a "CLI" change as such, as it's not an exposed CLI option. Only users who import `coder/envbuilder` would be affected by this.

> 3. I see the term magic used elsewhere in the code in relation to magic files, magic images and magic directives. Some of these come from the package I just renamed. Does `magic` have a specific definition that I'm unaware of? I fear that we might introduce confusion if the term magic somehow coupled these concepts.

It's just semantic bleed from `MagicDir`. If those can be renamed without any external effects, we could do so.
