### ISSUE TITLE
Change a devcontainer's image to an invalid image, causes a failed pod and the UI to loop endlessly

### ISSUE THREAD

**Issue by sharkymark** [coder/envbuilder#20]
`evnbuilder` should detect the image is incorrect, and fall back to the FALLBACK_IMAGE.

`kubectl` reveals the `CrashLoopBackOff` and the UI just stays in an endless loop.

You resolve it, in my example template, by choosing another Parameter devcontainer

![image](https://github.com/coder/envbuilder/assets/2022166/7e5498a8-0356-4613-b577-642862262cef)
![image](https://github.com/coder/envbuilder/assets/2022166/e5047597-35f1-47ec-bb88-18be858fa5dc)

**Comment by dannykopping** [comment]
Issue appears to be referencing the [devcontainer-kubernetes/main.tf](https://github.com/coder/coder/blob/main/examples/templates/devcontainer-kubernetes/main.tf) example template.

**Comment by dannykopping** [comment]
Passing the image name `invalid-image` to envbuilder results in the fallback image being used.

![image](https://github.com/coder/envbuilder/assets/373762/c5765243-6d8b-40a1-9e10-c0d5f70a228a)

Build logs:

```bash
envbuilder - Build development environments from repositories in a container
#1: 📦 Cloning invalid-url to /workspaces/invalid-url...
Failed to clone repository: clone "invalid-url": exec: "git": executable file not found in $PATH
Falling back to the default image...
#2: Deleting filesystem...
#2: 🏗️ Building image...
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
...
```

```bash
$ coder ssh bob
coder@coder-danny-bob-69b8f664ff-fk6c4:/workspaces$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

This satisfied the first clause of the feature:

https://pkg.go.dev/github.com/coder/envbuilder#section-readme

> `FallbackImage` specifies an alternative image to use when neither an image is declared in the devcontainer.json file nor a Dockerfile is present.

I'm now going to test out how it behaves when an _invalid_ devcontainer/Dockerfile works.

**Comment by dannykopping** [comment]
An invalid devcontainer also falls back just fine:

I used [this devcontainer](https://github.com/dannykopping/godevcontainer/blob/aa64890731451da567fd17f1d1770fb583d8dc67/.devcontainer/devcontainer.json#L3): (note the invalid JSON).

```bash
#1: 📦 Cloned repository! [1.178864329s]
Failed to parse devcontainer.json: standardize json: hujson: line 5, column 5: invalid character ']' after object value (expecting ',' or '}')
Falling back to the default image...
#2: Deleting filesystem...
#2: 🏗️ Building image...
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
```

```bash
$ coder ssh bob
coder@coder-danny-bob-84998f4f99-5z9cb:/workspaces$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by dannykopping** [comment]
An invalid Dockerfile also falls back just fine:

I used [this devcontainer](https://github.com/dannykopping/godevcontainer/blob/bb482c8f9eee26bbd89c023c18c0c61788218b38/.devcontainer/devcontainer.json): (note the invalid [Dockerfile](https://github.com/dannykopping/godevcontainer/blob/bb482c8f9eee26bbd89c023c18c0c61788218b38/.devcontainer/Dockerfile))

```bash
#1: 📦 Cloned repository! [851.098596ms]
#2: Deleting filesystem...
#2: 🏗️ Building image...
Failed to build: parsing dockerfile: dockerfile parse error on line 1: unknown instruction: INVALID
Falling back to the default image...
#2: Deleting filesystem...
#3: 🏗️ Building image...
#2: Retrieving image manifest codercom/enterprise-base:ubuntu
...
```

```bash
$ coder ssh bob
coder@coder-danny-bob-84998f4f99-5z9cb:/workspaces$ cat /etc/os-release
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by dannykopping** [comment]
Closing, this bug no longer exists.

**Comment by dannykopping** [comment]
This was fixed by https://github.com/coder/envbuilder/pull/30
