### ISSUE TITLE
coder/kaniko: support multi-stage builds with DoCacheProbe

### ISSUE THREAD

**Issue by johnstcn** [coder/envbuilder#230]
https://github.com/coder/kaniko/pull/12 added support for performing a 'fake' build (e.g. ProbeCache) 

However, this does not appear to work with multi-stage builds (https://github.com/coder/kaniko/pull/12#issuecomment-2160534514)

Add support for multi-stage builds. This will require changes to our Kaniko fork.

**Comment by mafredri** [comment]
To support multi-stage cache probes, we'll need a way to deduce the hash of dependencies between stages when operating in cache probe-mode.

Some ideas off the top of my head:

1. Use a tar reader/filesystem on the previous stage cache archive
    - Kaniko uses `os` and reads files directly, this will fail unless the previous stage has been extracted
    - Potentially slow, may require decompression and reading of the entire archive
    - Faster than normal extraction, small files are part of the tar stream and don't add overhead
2. Allow cached stage to be extracted
	- Slow, potentially very little benefit in cache probing
3. Modify cache archive/image to include metadata (i.e. file hashes of cross-stage dependencies)?
	- Probably doable, we can pre-compute cross-stage dependencies
	- Probably jank
4. Through some magic, allow the stage archive/hash to represent the cache-ability of the directive

I'm open to better ideas here.
