### ISSUE TITLE
Add support for postCreateCommand

### ISSUE THREAD

**Issue by bilby91** [coder/envbuilder#34]
Hello,

I've been waiting for this feature in coder for a long time to I'm really excited about helping test the initial versions.

One thing I noticed today was that the `postCreateCommand` doesn't seem to get executed. Is there any idea on how this should be implemented? I'm happy to contribute with this and get myself familiarized with the codebase.

**Comment by bpmct** [comment]
+1. Would be cool if this ran as something in the startup script

**Comment by aaronlehmann** [comment]
+1 from me as well, this would be very useful.

**Comment by pbabbott** [comment]
This would be great! Or at least mention that its not set up yet...
