### ISSUE TITLE
Dockerfile when using ARG in FROM doesn't work

### ISSUE THREAD

**Issue by bilby91** [coder/envbuilder#35]
I was testing the project using this devcontainer specification and envbuilder is failing to build the following Dockerfile => https://github.com/crunchloop/rails-interview/blob/main/.devcontainer/Dockerfile#L3

It throws and error indicating that it can't parse the image. This is working fine with devcontainer cli. I'm going to post the error soon since I don't have it with me.

Removing the `VARIANT` and hard coding the value made it work.

**Comment by bilby91** [comment]
Got some time to capture the error:

```
2023-07-18T20:22:02.964 app[91857917c5d783] eze [info] error: compile devcontainer.json: parse image from dockerfile: parse image ref "mcr.microsoft.com/devcontainers/ruby:${VARIANT}": could not parse reference: mcr.microsoft.com/devcontainers/ruby:${VARIANT}
```

**Comment by kylecarbs** [comment]
Ahh, will fix this!

**Comment by bilby91** [comment]
@kylecarbs Confirmed that this is working now!

**Comment by kylecarbs** [comment]
Fantastic!
