### ISSUE TITLE
cannot unmarshal string into Go struct field Spec.features of type map[string]interface {}

### ISSUE THREAD

**Issue by Tirzono** [coder/envbuilder#36]
I am trying the example template for devcontainers in Coder, and one of the options is the repository of vercel/next.js. However, when I use that example, I get this error:

```
#1: 📦 Cloning https://github.com/vercel/next.js to /workspaces/next.js...
#1: 📦 The repository already exists! [11.806867ms]
Failed to parse devcontainer.json: json: cannot unmarshal string into Go struct field Spec.features of type map[string]interface {}
Falling back to the default image...
```

Is this something on the envbuilder side or something on the next.js side?

It doesn't affect me really because it was just an example to get things running, but thought it was worth posting it here in case it's something on the envbuilder side.

**Comment by kylecarbs** [comment]
Thanks @Tirzono! This was my bad!
