### ISSUE TITLE
Defers run in `cmd/envbuilder` won't execute because Run performs `execve(2)`

### ISSUE THREAD

**Issue by mafredri** [coder/envbuilder#364]
Review: Even though we've fixed defers here, there's still `cmd/envbuilder` where e.g. `closeLogs` won't fire since we execve(2) after this.

_Originally posted by @mafredri in https://github.com/coder/envbuilder/pull/359#discussion_r1777477126_

**Comment by johnstcn** [comment]
We could maybe add a `PreExec []func()` field to `envbuilder.Options` that will get called right before we `Exec`?

**Comment by johnstcn** [comment]
Need to be careful about LogSenderV2 (see https://github.com/coder/envbuilder/pull/371); will fix this later.
