### ISSUE TITLE
Deal with devcontainer.json "liberties"

### ISSUE THREAD

**Issue by geiseri** [coder/envbuilder#38]
It looks like envbuilder's json parser is not okay with trailing `,` in arrays, or json comments.  Not sure what can be done with this, as I assume its using a 3rd party parser that might not support vscode's liberties taken with json.

**Comment by aaronlehmann** [comment]
Yeah, devcontainer.json files seem to routinely include nonstandard JSON like comments and trailing commas. In one of my projects, I'm using github.com/trapcodeio/go-strip-json-comments to strip both comments and trailing commas.

**Comment by kylecarbs** [comment]
Ahh, I'll fix this!
