### ISSUE TITLE
how can I clone repos to `/home/coder`?

### ISSUE THREAD

**Issue by bpmct** [coder/envbuilder#384]
By default, envbuilder will clone workspaces to `/workspaces/<repo-name>`. However, when I configure `ENVBUILDER_WORKSPACE_FOLDER` to `/home/coder`, it clones it directly in that folder, not `/home/coder/<repo-name>`.

What can I do here?

**Comment by bpmct** [comment]
@johnstcn @mafredri is this possible?

**Comment by johnstcn** [comment]
I think we need to append `path.Base(parsed.Path)` to `options.WorkspaceFolder` like we do for `DefaultWorkspaceFolder` https://github.com/coder/envbuilder/blob/main/options/defaults.go#L21-L38

**Comment by bpmct** [comment]
Gotcha... I think this will be a `must` for folks who maintain images where they wish to store projects in a single PVC with customizations (e.g. vs code settings) and repos

**Comment by johnstcn** [comment]
Adding to next sprint

**Comment by mafredri** [comment]
I started looking at this and I realized the feature is behaving exactly as documented: https://github.com/coder/envbuilder/blob/c16ae9fb1b24445b17439f9b5222940e26903d14/docs/using-local-files.md

Do we want to:
1. keep this behavior
2. update the docs and turn this into a breaking change
3. add a new option that changes the default workspace_s_ folder from `/workspace`

Thoughts @bpmct?

**Comment by bpmct** [comment]
Could we support the repo-name as a wildcard? So the default _workspaces_ folder changes to /workspace/$REPO (unsure what is best syntax) so someone can change it to `/home/$REPO`? That way, it can stay hardcoded to a folder or create a folder for the repo if it doesn't exist if wildcard is used

**Comment by bpmct** [comment]
Really though, I have no strong opinions and am down to deprecate a flag
but let’s avoid any hard breaking changes.
