### ISSUE TITLE
Envbuilder does not run in a sysbox container

### ISSUE THREAD

**Issue by janLo** [coder/envbuilder#50]
Envbuilder fails if it runs using the sysbox container runtime. This is unfortunate because sysbox is neccessary to run k3s or docker within a workspace.

The issue is described already in the kaniko project: https://github.com/GoogleContainerTools/kaniko/issues/2144 and the sysbox project: https://github.com/nestybox/sysbox/issues/564

There are also workarounds proposed (like unmounting the offending mountpoint or mounting something empty over it). As envbuilder uses kaniko internally, but the image lacks the userland for the workarounds I think, it should also implement the workaround for convenience.

Another option is to attach an empty volume from the outside to the container, but this is difficult to implement in a terraform manifest as the target of the mountpoint is dependend on the running kernel of the host - and the provisioner does not have this information available.

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/envbuilder/pull/183 and https://github.com/coder/envbuilder/pull/51
