### ISSUE TITLE
Dockerfile ARG replacement doesnt remove quotes from strings

### ISSUE THREAD

**Issue by twsl** [coder/envbuilder#78]
If you build a Dockerfile in your `devcontainer.json` that includes the following code:
```
ARG VARIANT="3.10"
FROM mcr.microsoft.com/devcontainers/python:0-${VARIANT}
```
or something similar where a string is used with quotes then you get the following error:
`error: compile devcontainer.json: parse image from dockerfile: parse image ref "mcr.microsoft.com/devcontainers/python:0-${VARIANT}\r": could not parse reference: mcr.microsoft.com/devcontainers/python:0-"3.10"`

**Comment by kylecarbs** [comment]
Will fix!
