### ISSUE TITLE
Document the differences in devcontainer specification implementation

### ISSUE THREAD

**Issue by kylecarbs** [coder/envbuilder#8]
e.g. mounts aren't supported

**Comment by evilhamsterman** [comment]
@kylecarbs why is this even an issue, you removed documentation about this yourself in commit ca6eccf. I understand that it's a fast moving project and the support may be changing rapidly but having at least some of the information would be helpful

**Comment by kylecarbs** [comment]
The support section I removed in that commit wasn't very complete, so it felt weird to mention _some_ things that aren't supported.

I agree this info is helpful - we'll prioritize this.

**Comment by evilhamsterman** [comment]
I think the way it was documenting what subset you do support would be a good way to deal with it.

**Comment by kylecarbs** [comment]
Reasonable, that's how we'll do it.

**Comment by matifali** [comment]
Are there plans to support mounts?
cc: @bpmct 
An example devcontainer that uses mounts and I am unable to build with `envbuilder` is:
https://github.com/railwayapp/nixpacks

**Comment by mafredri** [comment]
It's a bit early to tell, but there is a chance that the solution we land on for #128 _may_ enable passing the list of volumes to Terraform, which can then be made available for the template author. However, it's a bit unclear to me if we can turn it into a robust implementation that is easily usable between different cloud providers and container runtimes.

**Comment by mafredri** [comment]
Updated list or differences:

- No support for volumes (yet)
- Feature init scripts (entrypoint) are not supported (yet)

Please add more as they are discovered.
