### ISSUE TITLE
`postCreateCommand` does not execute

### ISSUE THREAD

**Issue by ericpaulsen** [coder/envbuilder#80]
Dev containers support a `postCreateCommand` parameter, to execute commands once the devcontainer is rebuilt:

```
"postCreateCommand": "bash scripts/install-dependencies.sh"
```

this is not run when using `envbuilder:latest`

**Comment by aaronlehmann** [comment]
`postCreateCommand` is supported by envbuilder. [This test](https://github.com/coder/envbuilder/blob/657306c7ce5ebf262ec975a3856c5f44deed64bc/integration/integration_test.go#L431) verifies that it executes. Do you have a `devcontainer.json` that reproduces the problem?

**Comment by ericpaulsen** [comment]
@aaronlehmann thank you - I ran my devcontainer again and validated `postCreateCommand` executed correctly. I must've gotten it mixed up with another parameter. closing out.
