### ISSUE TITLE
Rename project to "devcontainer"

### ISSUE THREAD

**Issue by ammario** [coder/envbuilder#82]
There is great demand to use devcontainers with coder, but this project's name makes it difficult for those users to find it.

cc @kylecarbs

**Comment by kylecarbs** [comment]
Calling it `devcontainer` is kind of weird because it's a devcontainer implementation in Go. I'm not a fan of the `go-` abbreviation because this is also somewhat of a unique implementation that relieves some of the rigidity of the JavaScript one.

Maybe `devcontainer-builder`?

**Comment by matifali** [comment]
May I suggest `devbuilder`?

**Comment by ammario** [comment]
> Calling it devcontainer is kind of weird because it's a devcontainer implementation in Go. 

Kind of confused by this since devcontainer is supposed to be an open spec and this is an implementation of it.

**Comment by matifali** [comment]
@bpmct, if we plan to support other filespecs as requested in #113. We should not change the name and the current name `envbuilder` is the most suitable.

**Comment by bpmct** [comment]
We're kind of landing on envbuilder... Closing for now
